### ISSUE TITLE
Missing DCSync Account

### ISSUE THREAD

**Issue by init5-SF** [Leo4j/Invoke-ADEnum#1]
Hello, I was giving this tool a spin and it works great, but it seems to have missed accounts with DCSync privs

Tool result
![image](https://github.com/Leo4j/Invoke-ADEnum/assets/10214861/eb0f02f0-9c73-444c-97a0-0d0ac1cab27c)

Missed principals
![image](https://github.com/Leo4j/Invoke-ADEnum/assets/10214861/cfd17606-333b-4dcb-8952-764b8cd89802)

**Comment by Leo4j** [comment]
Hi, thanks for raising this.
Could you please try running the powerview command to check for principals with dcsync permissions and see if it’s listed in the results?
If powerview misses that, then adenum will too.
If you could also try and dcsync using that account then we would have 100% certainty the account can dcsync.
Thanks

**Comment by Leo4j** [comment]
Closing as not getting an answer back, and moving ADEnum away from powerview
