### ISSUE TITLE
Exception calling ".ctor" with "2" argument(s): "Value cannot be null. Parameter name: binaryForm"

### ISSUE THREAD

**Issue by bill-e-ghote** [Leo4j/Invoke-ADEnum#5]
I'm using the tool to enumerate an enterprise AD environment and am encountering large number of errors in the output.
Please advise.

>> TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "Value cannot be null.
Parameter name: binaryForm""
>> TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "Value cannot be null.
Parameter name: binaryForm""
>> TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "Value cannot be null.
Parameter name: binaryForm""
PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "Value cannot be null.
Parameter name: binaryForm""
>> TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "Value cannot be null.
Parameter name: binaryForm""

![image](https://github.com/user-attachments/assets/b4b8dab9-bc10-46be-9140-5d3d49f6bd79)

**Comment by Leo4j** [comment]
Hi there, I find it difficult to advice on errors without context.

Did the tool run ? Did it create an html and txt file ?
Do you see results in there ?
Did you find the errors in the txt file ?
